# -*- Makefile -*-

# Set the name of the project here
PROJECT_NAME := LAV
PROJ_VERSION := 0.01

# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /home/alextrax/FV_project/LAV/llvm-3.3.src

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /home/alextrax/FV_project/LAV/llvm-3.3.src

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/alextrax/FV_project/LAV/LAV)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,@abs_top_objdir@)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /home/alextrax/FV_project/LAV/LAV/install

CFLAGS := -g -O2
CXXFLAGS := -g -O2
LDFLAGS := 

ENABLE_BOOLECTOR := 0
ENABLE_MATHSAT := 0
ENABLE_Z3 := 0
ENABLE_YICES := 1
